version: '2.0'
services:
  web:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres/postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password